# Generated by Django 4.2.2 on 2023-09-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_workdays_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workdays',
            options={'default_related_name': 'work_days', 'verbose_name': 'day', 'verbose_name_plural': 'days'},
        ),
        migrations.AlterField(
            model_name='workdays',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
